/* WHICH OF THE EVENTS DOES A PLAYED HOUSE EVER MEET? — the audit after nine releases

   `EVENTS` is the largest content table in the file and no audit has ever counted its reach. The
   question is the one #131, #173 and `meet.mjs` were all about, and the only one worth asking of
   written content: **does a played house ever see this, and if not, is it because the door is shut
   or because the door is somewhere else?**

   THE INSTRUMENT NEEDS NO INSTRUMENT, WHICH IS WHY THIS IS CHEAP AND TRUSTWORTHY. The obvious
   approaches are all traps:
     · patching `A.pickEvent` is a SILENT NO-OP — the handle holds copied references and the engine
       calls the module-scope binding (#173, proven by measuring rather than assuming);
     · calling `A.pickEvent(d)` to see what it would return CONSUMES RNG, so the probe would
       desynchronise the run it is measuring;
     · reading `d.pendingEvent` after the week misses everything, because the rope answers events
       inside the week and clears it.
   The rope already keeps the record: `did.events[ev.id]` is incremented where it answers one. This
   reads that. No patch, no perturbation, no reconstruction of a gate the game already has.

   TWO KINDS OF UNSEEN, and the distinction is the whole finding. An entry whose `make` takes the
   save — `make(d){…}` — is offered by `pickEvent` and can be gated shut. An entry whose `make` takes
   NOTHING — `make(){ return null; }` — is never generated by `pickEvent` at all; it is pushed onto
   `d.pendingEvent` by some other system, the way the war's second door works. `make.length` tells
   the two apart with no guessing.

   Every figure here is a COUNT or a SHARE. v3.64.0's rule.

   Usage: node test/probes/events.mjs [houses per prefix] [weeks] [seed]
*/
import { serve, open } from "../harness.mjs";
const H = +(process.argv[2] || 24), W = +(process.argv[3] || 420), SEED = process.argv[4] || "EVT";

const { server, port } = await serve({ page:"dist/test.html" });
const { browser, p } = await open(port);

const out = await p.evaluate(([H,W,SEED])=>{
  const A = window.__LVDVS, R = window.__ROPE;
  const PRES = [`${SEED}-1`, `${SEED}-2`, `${SEED}-3`];
  const KEYS = Object.keys(A.EVENTS);
  /* make(d) is offered by pickEvent; make() is pushed by something else entirely */
  const pushed = {};
  for(const k of KEYS){
    const m = A.EVENTS[k] && A.EVENTS[k].make;
    pushed[k] = typeof m === "function" ? m.length === 0 : null;
  }
  const seen = {}, byHouse = {};
  let weeks = 0, houses = 0, alive = 0;
  /* ---- WHAT THE REFERENCE PLAYER NEVER DOES, COUNTED RATHER THAN GREPPED ----
     `owedLife` gates on `d.flags.everCloth`, which only `recordCloth` sets — and `recordCloth` is
     what throwing the cloth to spare a beaten man calls. `courted` is pushed only when the PLAYER
     courts a rival's man. Neither is a rope step. A grep of the harness says so; a count says so
     with a denominator, which is the difference between an assertion and a measurement. */
  let clothHouses = 0, clothTotal = 0, primacyHouses = 0;
  let primacyWeeks = 0, sixWeeks = 0, secondMan = 0, bothTerms = 0, eligUnknown = false;
  /* ---- TWO OF THESE COUNTERS WERE WRONG AND ONE WAS UNFALSIFIABLE ----
     `primacyHouses` first read `d.primus && d.primus.mine` AFTER the loop — which is "held it at the
     moment the house ended", not "ever held it", and 63 of 72 houses end dead. It is sampled inside
     the week now.
     And the poach counter read `d.poachedIn` and `d.flags.everCourted`, NEITHER OF WHICH EXISTS in
     `src/ludus.jsx` — both were invented here, so the counter could only ever return 0 and would
     have confirmed the hypothesis for free. It is deleted rather than fixed: `courted` never
     appearing in `did.events` across 16,300 house-weeks already says what it was meant to say, off
     a number the game itself keeps. */
  for(const pre of PRES){
    for(let h=0; h<H; h++){
      const d = A.newGameState("Ev"+h, "clean", `${pre}-${h}`, null);
      const mine = {};
      houses++;
      let w = 0, everPrimacy = false;
      for(; w<W; w++){
        if(d.over) break;
        const did = R.lanista(d);
        if(!d.lanista) break;
        weeks++;
        /* ---- #: WHICH TERM OF `primacy`'s GATE IS THE ONE THAT SHUTS? ----
           Corrected, 14 of 72 houses DO hold the city primacy — the first draft's counter said 0 and
           would have filed this as a rope blind spot, which it is not. So the event's other two
           terms are the question: a SECOND `primusEligible` man, and SIX WEEKS since taking it.
           Counted separately, off the game's own `primusEligible`, because "the gate never opened"
           does not say which term held it — `census` splits its four the same way. */
        if(d.primus && d.primus.mine){
          everPrimacy = true; primacyWeeks++;
          const held = d.week - (d.primus.since || 0);
          if(held >= 6) sixWeeks++;
          const others = A.activeG(d).filter(x => x.id !== d.primus.gid);
          const elig = A.primusEligible ? others.filter(x => A.primusEligible(x)) : null;
          if(elig === null) eligUnknown = true;
          else if(elig.length) secondMan++;
          if(held >= 6 && elig && elig.length) bothTerms++;
        }
        const evs = (did && did.events) || {};
        for(const k of Object.keys(evs)){
          seen[k] = (seen[k]||0) + evs[k];
          mine[k] = true;
        }
      }
      if(w >= W) alive++;
      const cloth = (d.flags && d.flags.everCloth) || 0;
      if(cloth > 0){ clothHouses++; clothTotal += cloth; }
      if(everPrimacy) primacyHouses++;
      for(const k of Object.keys(mine)) byHouse[k] = (byHouse[k]||0) + 1;
    }
  }
  return { KEYS, pushed, seen, byHouse, weeks, houses, alive, W, PRES,
           clothHouses, clothTotal, primacyHouses,
           primacyWeeks, sixWeeks, secondMan, bothTerms, eligUnknown };
}, [H, W, SEED]);

const { KEYS, pushed, seen, byHouse } = out;
const N = KEYS.length;
const met = KEYS.filter(k => seen[k]);
const unmet = KEYS.filter(k => !seen[k]);
const unmetOffered = unmet.filter(k => pushed[k] === false);
const unmetPushed  = unmet.filter(k => pushed[k] === true);

console.log(`\nWHICH OF THE EVENTS DOES A PLAYED HOUSE EVER MEET?`);
console.log(`${out.houses} houses over ${out.weeks} house-weeks, ${out.PRES.length} seed prefixes, ${out.alive} still alive at ${out.W}w\n`);
console.log(`  entries in the table            ${N}`);
console.log(`  met at least once               ${met.length}  (${(met.length/N*100).toFixed(0)}%)`);
console.log(`  never met                       ${unmet.length}`);
console.log(`    of those, OFFERED by pickEvent and never taken   ${unmetOffered.length}`);
console.log(`    of those, never offered at all — make() pushes   ${unmetPushed.length}`);

if(unmetOffered.length){
  console.log(`\n  NEVER SEEN THOUGH \`pickEvent\` CAN OFFER THEM — the door is shut:`);
  console.log(`    ${unmetOffered.join(" · ")}`);
}
if(unmetPushed.length){
  console.log(`\n  never offered by \`pickEvent\` at all (\`make()\` takes no save — another system pushes these):`);
  console.log(`    ${unmetPushed.join(" · ")}`);
}

const rows = met.map(k => ({ k, n: seen[k], h: byHouse[k]||0 })).sort((a,b)=>b.n-a.n);
console.log(`\n  WHAT A HOUSE ACTUALLY MEETS, by houses that ever saw it (of ${out.houses}):`);
for(let i=0;i<rows.length;i+=3){
  console.log(`    ` + rows.slice(i,i+3).map(r =>
    `${r.k.padEnd(14)} ${String(r.h).padStart(3)}h ${String(r.n).padStart(5)}x`).join("   "));
}
const rare = rows.filter(r => r.h <= Math.max(1, Math.round(out.houses*0.05)));
console.log(`\n  seen by 5% of houses or fewer: ${rare.length ? rare.map(r=>`${r.k} (${r.h})`).join(" · ") : "none"}`);

/* ---------------- AND ARE THE UNMET ONES ACTUALLY UNREACHABLE? ----------------
   This is the half v3.66.0's audit got wrong the first time and had to correct: `dark.mjs` reported
   five dead buttons that were not dead, because its fixtures could not open the game's own gates.
   "The reference player never does X" and "X cannot happen" are different sentences, and the driven
   run above cannot tell them apart. So each unmet entry gets a state built to satisfy its own gate,
   and `pickEvent` is called against it. Calling `pickEvent` directly is legitimate HERE and was not
   above: this is a constructed fixture, not a live run, so consuming RNG desynchronises nothing. */
const reach = await p.evaluate((names)=>{
  const A = window.__LVDVS;
  const out = {};
  const tries = 400;
  const arm = {
    /* `owedLife` gates on `d.flags.everCloth` — set by `recordCloth`, which is what throwing the
       cloth to spare a beaten man calls. The rope has no mercy step at all. */
    owedLife: d => { d.flags.everCloth = 1; d.flags.owedDone = 0; d.arcs = []; },
    /* `primacy` wants the house to HOLD the city title for six weeks with a second eligible man */
    primacy: d => {
      const men = A.activeG(d);
      if(men.length < 2) return false;
      men.forEach(g => { g.wins = 12; g.pfame = 40; });
      d.primus = { mine:true, gid: men[0].id, since: 1 };
      d.week = 20;
    },
  };
  for(const k of names){
    const e = A.EVENTS[k];
    if(!e){ out[k] = { note:"no such entry" }; continue; }
    if(typeof e.make === "function" && e.make.length === 0){
      out[k] = { pushed:true, hasBuild: typeof e.build === "function",
        note:"never offered by pickEvent — pushed by another system, so a fixture here proves nothing" };
      continue;
    }
    let hit = 0, armed = true;
    for(let i=0;i<tries;i++){
      const d = A.newGameState("Rx", "clean", `REACH-${k}-${i}`, null);
      if(arm[k] && arm[k](d) === false){ armed = false; break; }
      let got = null;
      try { got = A.pickEvent(d); } catch(err){ out[k] = { err: err.message }; break; }
      if(got && got.id === k) hit++;
    }
    out[k] = Object.assign(out[k]||{}, { armed, hit, tries });
  }
  return out;
}, unmet);

console.log(`\n  WHAT THE REFERENCE PLAYER NEVER DOES — the reason the four are unmet, with a denominator:`);
console.log(`    houses that ever threw the cloth (\`everCloth\` > 0)   ${out.clothHouses} of ${out.houses}   — the gate \`owedLife\` asks for`);
console.log(`    times the cloth was thrown in all                     ${out.clothTotal}`);
console.log(`    houses that ever held the city primacy                ${out.primacyHouses} of ${out.houses}   — the gate \`primacy\` asks for`);
console.log(`\n    \`primacy\` asks THREE things at once; split, over the ${out.primacyWeeks} house-weeks holding it:`);
console.log(`      held it six weeks or more                    ${out.sixWeeks} of ${out.primacyWeeks}`);
console.log(`      had a second \`primusEligible\` man            ${out.eligUnknown ? "primusEligible is not on the handle — not guessed at" : `${out.secondMan} of ${out.primacyWeeks}`}`);
console.log(`      BOTH at once, which is what the event needs  ${out.eligUnknown ? "—" : `${out.bothTerms} of ${out.primacyWeeks}`}`);
console.log(`    (\`courted\` has no counter here on purpose: the two fields a first draft counted,`);
console.log(`     \`d.poachedIn\` and \`d.flags.everCourted\`, do not exist in the file. It never fired`);
console.log(`     in ${out.weeks} house-weeks, which is the game's own record and needs no help from mine.)`);

console.log(`\n  ARE THEY REACHABLE AT ALL? — each unmet entry given a state that satisfies its own gate.`);
console.log(`  Two different answers hide behind one column, so read this with the split above:`);
console.log(`    owedLife — the reference player never throws the cloth, so the gate is never even asked.`);
console.log(`    primacy  — the gate IS asked, on 6 of 99 house-weeks; at the offer rate below that is`);
console.log(`               about 0.4 expected firings over ${out.houses} houses, and 0 observed agrees with it.`);
for(const k of unmet){
  const r = reach[k] || {};
  if(r.pushed) console.log(`    ${k.padEnd(10)} ${r.note}${r.hasBuild ? " (it has a `build`, so its pusher is the thing to find)" : ""}`);
  else if(r.err) console.log(`    ${k.padEnd(10)} threw: ${r.err}`);
  else if(!r.armed) console.log(`    ${k.padEnd(10)} could not build a fair fixture — reported rather than guessed at`);
  else console.log(`    ${k.padEnd(10)} offered on ${r.hit} of ${r.tries} armed draws`
    + (r.hit ? `  <- REACHABLE with its own gate open. WHY a played house never meets it is the`
             + ` split above, and it is not the same answer for both`
             : `  <- still nothing with its own gate open`));
}
console.log();

await browser.close();
server.close();
